import type { InboxData } from "./schemas";

const NOW_MS = Date.now();
const MINUTE_MS = 60 * 1000;
const HOUR_MS = 60 * MINUTE_MS;
const DAY_MS = 24 * HOUR_MS;

const AUTHOR_AVATAR_URL = "https://i.pravatar.cc/100?img=32";
const REVIEWER_AVATAR_URL = "https://i.pravatar.cc/100?img=12";

export const MOCK_INBOX_DATA: InboxData = {
  mergeRequests: [
    {
      id: 501,
      iid: 1451,
      projectId: 7,
      sourceBranch: "feat/notifications-sound",
      title: "[TT-4911] - feat: connection boost",
      description: "Improve connection handling for offline mode.",
      state: "opened",
      createdAt: new Date(NOW_MS - 4 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 2 * HOUR_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1451",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: true,
      headPipeline: {
        id: 3101,
        iid: 211,
        projectId: 7,
        status: "success",
        source: "push",
        ref: "refs/merge-requests/1451/head",
        sha: "5c0d1f48d4fdc4a54d6122a595",
        webUrl: "https://gitlab.com/example/repo/-/pipelines/3101",
        createdAt: new Date(NOW_MS - 3 * HOUR_MS).toISOString(),
        updatedAt: new Date(NOW_MS - 2 * HOUR_MS).toISOString(),
      },
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 502,
      iid: 1452,
      projectId: 7,
      sourceBranch: "feat/pipeline-details",
      title: "[TT-5041] - feat: manage multi-events",
      description: "Expose more pipeline details in the UI.",
      state: "opened",
      createdAt: new Date(NOW_MS - 3 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 6 * HOUR_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1452",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: false,
      headPipeline: {
        id: 3102,
        iid: 212,
        projectId: 7,
        status: "failed",
        source: "push",
        ref: "refs/merge-requests/1452/head",
        sha: "a9b4ee3321a3af1e0d11d7a7b3",
        webUrl: "https://gitlab.com/example/repo/-/pipelines/3102",
        createdAt: new Date(NOW_MS - 7 * HOUR_MS).toISOString(),
        updatedAt: new Date(NOW_MS - 6 * HOUR_MS).toISOString(),
      },
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 503,
      iid: 1453,
      projectId: 7,
      sourceBranch: "bugfix/audit-kyd",
      title: "bugfix/TT-5061: fix audit kyd/kyc/k...",
      description: "Patch audit pipeline failures.",
      state: "opened",
      createdAt: new Date(NOW_MS - 2 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 10 * HOUR_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1453",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: true,
      blockingDiscussionsResolved: false,
      headPipeline: {
        id: 3103,
        iid: 213,
        projectId: 7,
        status: "running",
        source: "push",
        ref: "refs/merge-requests/1453/head",
        sha: "3fe3a021d8b11fc8b25d8dd1cf",
        webUrl: "https://gitlab.com/example/repo/-/pipelines/3103",
        createdAt: new Date(NOW_MS - 11 * HOUR_MS).toISOString(),
        updatedAt: new Date(NOW_MS - 10 * HOUR_MS).toISOString(),
      },
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 504,
      iid: 1454,
      projectId: 7,
      sourceBranch: "feat/reference-tab",
      title: "TT-5054 Add missing reference tab...",
      description: "Add missing reference tab and align icons.",
      state: "opened",
      createdAt: new Date(NOW_MS - 5 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 26 * HOUR_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1454",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: true,
      headPipeline: null,
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 505,
      iid: 1455,
      projectId: 7,
      sourceBranch: "chore/refactor-apis",
      title: "chore: refactor API client wiring",
      description: "Restructure command plumbing for new endpoints.",
      state: "opened",
      createdAt: new Date(NOW_MS - 6 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 2 * DAY_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1455",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: true,
      headPipeline: null,
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 506,
      iid: 1456,
      projectId: 7,
      sourceBranch: "feat/sounds",
      title: "feat: add sound preference for notifications",
      description: "Allow users to toggle and pick a sound.",
      state: "opened",
      createdAt: new Date(NOW_MS - 7 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 3 * DAY_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1456",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: true,
      headPipeline: null,
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 507,
      iid: 1457,
      projectId: 7,
      sourceBranch: "feat/triage-colors",
      title: "feat: triage label colors for inbox",
      description: "Expose label colors in list rows.",
      state: "opened",
      createdAt: new Date(NOW_MS - 8 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 4 * DAY_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1457",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: true,
      headPipeline: null,
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 508,
      iid: 1458,
      projectId: 7,
      sourceBranch: "feat/compact-mode",
      title: "feat: compact mode for dense inbox",
      description: "Add a compact density preset.",
      state: "opened",
      createdAt: new Date(NOW_MS - 9 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 5 * DAY_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1458",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: true,
      headPipeline: null,
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 509,
      iid: 1459,
      projectId: 7,
      sourceBranch: "feat/filter-presets",
      title: "feat: filter presets for inbox",
      description: "Save quick filters per tab.",
      state: "opened",
      createdAt: new Date(NOW_MS - 10 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 6 * DAY_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1459",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: true,
      headPipeline: null,
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 510,
      iid: 1460,
      projectId: 7,
      sourceBranch: "feat/pinned-mrs",
      title: "feat: pin merge requests to top",
      description: "Allow pinning favorite MRs.",
      state: "opened",
      createdAt: new Date(NOW_MS - 11 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 7 * DAY_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1460",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: true,
      headPipeline: null,
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 511,
      iid: 1461,
      projectId: 7,
      sourceBranch: "feat/quick-actions",
      title: "feat: quick actions on inbox rows",
      description: "Add approve/merge shortcuts.",
      state: "opened",
      createdAt: new Date(NOW_MS - 12 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 8 * DAY_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1461",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: true,
      headPipeline: null,
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
    {
      id: 512,
      iid: 1462,
      projectId: 7,
      sourceBranch: "chore/cleanup-hooks",
      title: "chore: cleanup hooks dependencies",
      description: "Remove unused deps in hooks.",
      state: "opened",
      createdAt: new Date(NOW_MS - 13 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 9 * DAY_MS).toISOString(),
      webUrl: "https://gitlab.com/example/repo/-/merge_requests/1462",
      author: {
        id: 42,
        username: "godart-corentin",
        name: "Godart Corentin",
        avatarUrl: AUTHOR_AVATAR_URL,
      },
      hasConflicts: false,
      blockingDiscussionsResolved: true,
      headPipeline: null,
      draft: false,
      workInProgress: false,
      isReviewer: false,
      approvedByMe: false,
    },
  ],
  todos: [
    {
      id: 9101,
      projectId: 7,
      author: {
        id: 64,
        username: "reviewer",
        name: "Code Reviewer",
        avatarUrl: REVIEWER_AVATAR_URL,
      },
      actionName: "commented",
      targetType: "MergeRequest",
      targetUrl: "https://gitlab.com/example/repo/-/merge_requests/1451",
      target: null,
      body: "Can we add a test for the new keyboard nav?",
      state: "pending",
      createdAt: new Date(NOW_MS - 45 * MINUTE_MS).toISOString(),
    },
    {
      id: 9102,
      projectId: 7,
      author: {
        id: 65,
        username: "qa",
        name: "QA Lead",
        avatarUrl: REVIEWER_AVATAR_URL,
      },
      actionName: "mentioned",
      targetType: "MergeRequest",
      targetUrl: "https://gitlab.com/example/repo/-/merge_requests/1453",
      target: null,
      body: "Please add a regression note for QA.",
      state: "pending",
      createdAt: new Date(NOW_MS - 90 * MINUTE_MS).toISOString(),
    },
    {
      id: 9103,
      projectId: 7,
      author: {
        id: 66,
        username: "devrel",
        name: "DevRel",
        avatarUrl: REVIEWER_AVATAR_URL,
      },
      actionName: "commented",
      targetType: "MergeRequest",
      targetUrl: "https://gitlab.com/example/repo/-/merge_requests/1454",
      target: null,
      body: "Can we update the changelog wording?",
      state: "pending",
      createdAt: new Date(NOW_MS - 3 * HOUR_MS).toISOString(),
    },
  ],
  pipelines: [
    {
      id: 4001,
      iid: 301,
      projectId: 7,
      status: "success",
      source: "push",
      ref: "main",
      sha: "bfc2aef7b1a2a21a7f6d6b424d",
      webUrl: "https://gitlab.com/example/repo/-/pipelines/4001",
      createdAt: new Date(NOW_MS - 5 * HOUR_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 4 * HOUR_MS).toISOString(),
    },
    {
      id: 4002,
      iid: 302,
      projectId: 7,
      status: "failed",
      source: "merge_request_event",
      ref: "refs/merge-requests/1452/head",
      sha: "0e8d742c3d9cda56a2c9161a8e",
      webUrl: "https://gitlab.com/example/repo/-/pipelines/4002",
      createdAt: new Date(NOW_MS - 9 * HOUR_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 8 * HOUR_MS).toISOString(),
    },
    {
      id: 4003,
      iid: 303,
      projectId: 7,
      status: "running",
      source: "schedule",
      ref: "nightly",
      sha: "9bc88b7c1c1b40a0f6a4d7f321",
      webUrl: "https://gitlab.com/example/repo/-/pipelines/4003",
      createdAt: new Date(NOW_MS - 90 * MINUTE_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 30 * MINUTE_MS).toISOString(),
    },
    {
      id: 4004,
      iid: 304,
      projectId: 7,
      status: "canceled",
      source: "push",
      ref: "feature/better-tooltips",
      sha: "c1e9b1a3d8f044f0aa2fdc5b1a",
      webUrl: "https://gitlab.com/example/repo/-/pipelines/4004",
      createdAt: new Date(NOW_MS - 2 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 2 * DAY_MS + 30 * MINUTE_MS).toISOString(),
    },
    {
      id: 4005,
      iid: 305,
      projectId: 7,
      status: "success",
      source: "schedule",
      ref: "nightly",
      sha: "ddc90b2d0f7ab1e34b21d6a1b2",
      webUrl: "https://gitlab.com/example/repo/-/pipelines/4005",
      createdAt: new Date(NOW_MS - 3 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 3 * DAY_MS + 20 * MINUTE_MS).toISOString(),
    },
    {
      id: 4006,
      iid: 306,
      projectId: 7,
      status: "failed",
      source: "push",
      ref: "feature/visual-refresh",
      sha: "1a2b3c4d5e6f708192a3b4c5d6",
      webUrl: "https://gitlab.com/example/repo/-/pipelines/4006",
      createdAt: new Date(NOW_MS - 4 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 4 * DAY_MS + 40 * MINUTE_MS).toISOString(),
    },
    {
      id: 4007,
      iid: 307,
      projectId: 7,
      status: "running",
      source: "push",
      ref: "feature/gamefeel",
      sha: "9988aabbccddeeff0011223344",
      webUrl: "https://gitlab.com/example/repo/-/pipelines/4007",
      createdAt: new Date(NOW_MS - 6 * HOUR_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 2 * HOUR_MS).toISOString(),
    },
    {
      id: 4008,
      iid: 308,
      projectId: 7,
      status: "canceled",
      source: "merge_request_event",
      ref: "refs/merge-requests/1456/head",
      sha: "aa11bb22cc33dd44ee55ff66gg",
      webUrl: "https://gitlab.com/example/repo/-/pipelines/4008",
      createdAt: new Date(NOW_MS - 5 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 5 * DAY_MS + 10 * MINUTE_MS).toISOString(),
    },
    {
      id: 4009,
      iid: 309,
      projectId: 7,
      status: "success",
      source: "push",
      ref: "hotfix/urgent-crash",
      sha: "0a1b2c3d4e5f66778899aabbcc",
      webUrl: "https://gitlab.com/example/repo/-/pipelines/4009",
      createdAt: new Date(NOW_MS - 6 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 6 * DAY_MS + 25 * MINUTE_MS).toISOString(),
    },
    {
      id: 4010,
      iid: 310,
      projectId: 7,
      status: "failed",
      source: "schedule",
      ref: "weekly",
      sha: "abcd1234ef567890abcd1234ef",
      webUrl: "https://gitlab.com/example/repo/-/pipelines/4010",
      createdAt: new Date(NOW_MS - 7 * DAY_MS).toISOString(),
      updatedAt: new Date(NOW_MS - 7 * DAY_MS + 55 * MINUTE_MS).toISOString(),
    },
  ],
};
